### ISSUE TITLE
I think that there should  be a footer added on the webpage

### ISSUE THREAD

**Issue by srishtij2000** [ProjectSakura/wiki#39]
I'd like to add a footer section

**Comment by ArunTeltia** [comment]
No footer is required because it's a spa we will be working on the page such that we don't need to scroll in this page and everything is tightly conjusted yet it will look good 

Footer will just create ambiguity in the side bar and in the whole page 

So for that reason I will suggest you to close this issue if you have anything better to suggest considering this 

Please suggest , will be happy to hear that 😄
